data:
  paths:
    - fchamp/data/dsl_2012_2026.csv
  delimiter: ","
  use_market: true
  xg_path: artifacts/xg_dsl.csv

elo:
  start: 1500
  k: 20
  hfa: 55
  mov_factor: 0.1
  season_regression: 0.2
  time_decay_days: 150.0
  adaptive_k: true
  home_away_split: true

features:
  rolling_n: 6
  ewm_alpha: 0.5
  max_goals: 8
  add_features: true
  safe_fill: true
  use_advanced_stats: true
  use_h2h: true
  use_xg_proxy: true
  use_xg_real: true
  h2h_matches: 6

model:
  alpha: 0.8
  use_dixon_coles: true
  dc_rho: 0.06
  use_ensemble: true
  ensemble_weight: 0.7
  robust_sanitization: true
  adaptive_clipping: true
  draw_weight: 2.3
  
  calibration:
    enabled: true
    method: isotonic

  gbm:
    enabled: true
    blend_weight: 0.7

  market_blend_weight: 0.35

  draw_booster:
    enabled: true
    elo_abs_diff_max: 24.5
    goals_ewm_sum_max: 2.88
    market_draw_min: 0.306
    weight: 0.21
    max_boost: 0.04
    promote_near_tie: true
    tie_margin: 0.12
    
  market_guardrails:
    enabled: true
    max_abs_diff_home: 0.18
    max_abs_diff_draw: 0.14
    max_abs_diff_away: 0.18
    blend_weight: 0.5

backtest:
  n_splits: 5
  gap: 1
  tune: true
  tune_trials: 100

artifacts_dir: artifacts/models_dsl